[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GaussMLE = "39799108-5025-4d0e-9a62-95a61c8c6061"
MicroscopePSFs = "de9ac726-48a4-48ab-84b0-1c03c7c18929"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SMLMBoxer = "a7d3b33b-b840-4f8e-b556-99be03134090"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
